spring.application.name=TechBazaar

#Database Configuration
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/tech_bazaar_db?characterEncoding=UTF-8
spring.datasource.username = root
spring.datasource.password = 

#Database Permission
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#Project Running Server Port
server.port = 8282

#File Size Configuration
spring.servlet.multipart.max-file-size = 25MB
spring.servlet.multipart.max-request-size = 25MB

#mail Configuration
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = princek65498@gmail.com
spring.mail.password = zyoh mkdm kndd vkdo
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

razorpay.key = rzp_live_Io1s9ctQtD0G1b
razorpay.secret = HO60ThPu65xyvH7ewH5eVcWp

